'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Foreign_Company
    Public Property ID As Integer
    Public Property Name As String
    Public Property PhoneNumber As String
    Public Property City As String
    Public Property Country As String
    Public Property EmployeeNum As Nullable(Of Integer)

    Public Overridable Property Calls As ICollection(Of [Call]) = New HashSet(Of [Call])

End Class
