'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CallLogDBEntities1
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CallLogDBEntities1")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property Employees() As DbSet(Of Employee)
    Public Overridable Property Foreign_Company() As DbSet(Of Foreign_Company)
    Public Overridable Property Calls() As DbSet(Of [Call])

End Class
